### PR TITLE
Register cost profiles with sif::CostFactory

### PR DESCRIPTION
**Pull request by ericrwolfe**
Switches Meili's register_costing logic to use sif::CostFactory.

Fixes an issue where only one of each sif::TravelMode can be used (e.g. auto, bus, etc all use kDrive).

### CODE REVIEW

**Comment by kevinkreiser** [comment]
awesome, i was just mentioning to @kdiluca that we should do this! thanks! @ptpt what do you say?

**Comment by ericrwolfe** [comment]
Give me a sec before you merge, tests pass but just noticed a runtime "Bus error: 10" because of this or possibly something I changed in my local version of sif. Let me get back to you!

**Comment by ericrwolfe** [comment]
Fixed

**Comment by ptpt** [comment]
This PR removes the method
```C++
MapMatcher* Create(sif::TravelMode, const boost::property_tree::ptree&);
```
which we haven't ever used and I think won't use in the future.

Looks great! I give it a :ship:. Thanks for the PR.

**Pull request merged**
