### PR TITLE
Make sure origin/dest match results have the same edgeids with the fi…

### PR DESCRIPTION
**Pull request by ptpt**
…rst/last edgesegment

### CODE REVIEW

**Comment by dnesbitt61** [comment]
This did not seem to fix the test case. Still has a single edge when it gets to trip path builder, and that single edge does not match the origin it finds. I have a hack in thor that we can use in the meantime if you don't have time to debug at this time.

**Comment by ptpt** [comment]
I suspect that the problem is that meili doesn't guarantee that a result's edgeid must match one of its path edges WHEN the path location is at a node. If so, this PR doesn't solve the problem.

Maybe you can make a fake origin pathlocation which contains the origin match's edgeid as a single path edge in THOR.

**Comment by dnesbitt61** [comment]
:shipit:

**Comment by ptpt** [comment]
This PR can't fix the issue. https://github.com/valhalla/thor/pull/525 should fix.

**Pull request closed without merging**
