### PR TITLE
Improve interpolation

### PR DESCRIPTION
**Pull request by ptpt**
- [x] Remove `graphtype()` from match result. See #40 
- [x] Improve measurement interpolation. Previously measurements were interpolated into projected point on the closest edge or the closest node, which is not always best. This PR will interpolate them into the projected point where transition cost + emission cost is minimal.
- [x] Fix minor interpolation issues (see screenshots below)

Before (3, 4, 5 not interpolated):
image

After (3, 4, 5 interpolated):
image

Before (2 interpolated incorrectly):
image

After (2 interpolated correctly):
image

### CODE REVIEW

**Comment by ptpt** [comment]
Anyone give it a review before ship @kevinkreiser @dnesbitt61

**Comment by kevinkreiser** [comment]
I've given it a look over and dont see anything wrong though it is a heck of a large PR! The pictures speak for themselves of course!

:rocket:

**Comment by ptpt** [comment]
Thanks Kevin. I feel I complicated the interpolation part but there seems no easier way to handle it.

Sorry for the huge PR. Will send small PRs only!

**Comment by kevinkreiser** [comment]
@ptpt no worries! sometimes theres no other option than a large PR!

**Pull request merged**
